name: wenzbak
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.0

# Add regular dependencies here.
dependencies:
  sqflite: ^2.3.0
  path: ^1.8.0
  crypto: ^3.0.0
  encrypt: ^5.0.0
  uuid: ^4.5.2
  synchronized: ^3.4.0
  http: ^1.1.0
  xml: ^6.3.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
